In [1]:
%matplotlib inline

from __future__ import absolute_import, print_function, unicode_literals, division
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import itertools
import random as rand
import copy

In [2]:
def mat_dbg(x):
    print(x.shape, ": \n", x)

In [160]:
class MLP(object):
    """
    NOTE: Matrix operations are modified from RBM file
    In particular, we have an an an input of n data points with
    dimension d as a d-by-n matrix
    """
    def __init__(self, data, num_hidden, learn_rate):
        self.data = data
        self.num_data = data.shape[1]
        self.num_visible = data.shape[0]
        self.num_hidden = num_hidden
        self.learn_rate = learn_rate
        
        self.weights = np.random.rand(self.num_visible, self.num_hidden)
        self.weights = np.insert(self.weights, 0, 0, axis = 0)
        self.data = np.insert(self.data, 0, 1, axis = 0)
        
        #mat_dbg(self.weights.T)
        #mat_dbg(self.data)
    
    def _sigmoid(self,x):
        return 1.0/(1.0+np.exp(-x))
        
    def _activated(self):
        activated = self._sigmoid(np.dot(self.weights.T,self.data)) 
        mat_dbg(activated)
        activated = np.sign(activated - 0.5)
        for elt in np.nditer(activated,op_flags=['readwrite']):
            if elt == 0: 
                elt[...] = 1
        return activated
    
    def _feed_forward(self):
        error = self.weights.T - self._activated()
        prods = np.dot(error.T,self._activated())
        delta = np.dot(self.learn_rate,prods)
        print("Feed forward outputs. ")
        mat_dbg(error)
        mat_dbg(prods)
        mat_dbg(self._activated())
        return delta
        
    def _prop_backward(self):
        return None
    
    def _calc_error(self):
        return None
        

In [165]:
sample_data = np.sign(1-2*np.random.rand(3,4))
mat_dbg(sample_data)
MLP_1 = MLP(sample_data,2,0.05)
print(MLP_1.weights.T)
#MLP_1._activated()
MLP_1._feed_forward()
print(MLP_1.weights.T)

(3, 4) : 
 [[-1.  1. -1. -1.]
 [ 1. -1. -1. -1.]
 [-1.  1.  1. -1.]]
[[ 0.          0.45627034  0.08831604  0.25241668]
 [ 0.          0.13669429  0.64497069  0.97419815]]
(2, 4) : 
 [[ 0.34969708  0.65030292  0.42747277  0.31066696]
 [ 0.38558196  0.61441804  0.54798515  0.14730921]]
(2, 4) : 
 [[ 0.34969708  0.65030292  0.42747277  0.31066696]
 [ 0.38558196  0.61441804  0.54798515  0.14730921]]
Feed forward outputs. 
(2, 4) : 
 [[ 1.         -0.54372966  1.08831604  1.25241668]
 [ 1.         -0.86330571 -0.35502931  1.97419815]]
(4, 4) : 
 [[-2.          2.          0.         -2.        ]
 [ 1.40703537 -1.40703537 -0.31957604  1.40703537]
 [-0.73328673  0.73328673 -1.44334536 -0.73328673]
 [-3.22661483  3.22661483  0.72178147 -3.22661483]]
(2, 4) : 
 [[ 0.34969708  0.65030292  0.42747277  0.31066696]
 [ 0.38558196  0.61441804  0.54798515  0.14730921]]
(2, 4) : 
 [[-1.  1. -1. -1.]
 [-1.  1.  1. -1.]]
[[ 0.          0.45627034  0.08831604  0.25241668]
 [ 0.          0.13669429  0.644

In [166]:
print(MLP_1.weights.T)

[[ 0.          0.45627034  0.08831604  0.25241668]
 [ 0.          0.13669429  0.64497069  0.97419815]]
