In [384]:
%matplotlib inline

from __future__ import absolute_import, print_function, unicode_literals, division
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import itertools
import random as rand
import copy

In [385]:
def mat_dbg(x):
    print(x.shape, ": \n", x)

In [667]:
class MLP(object):
    """
    NOTE: Matrix operations are modified from RBM file
    In particular, we have an an an input of n data points with
    dimension d as a d-by-n matrix
    """
    def __init__(self, data, num_hidden, learn_rate):
        # First row are the target values
        self.targets = data[0]
        self.data = data[1:,:]
        self.num_data = data.shape[1]
        self.num_visible = data.shape[0] - 1
        self.num_hidden = num_hidden
        self.learn_rate = learn_rate
        
        self.weights = np.random.rand(self.num_visible, self.num_hidden)
        self.weights = np.insert(self.weights, 0, 1, axis = 0)
        self.data = np.insert(self.data, 0, 1, axis = 0)
    
    def _sigmoid(self,x):
        return 1.0/(1.0+np.exp(-x))
        
    def _activated(self,mat):
        activated = self._sigmoid(np.dot(self.weights.T,mat))
        #activated = np.sign(activated - 0.5) # -0.5 for logistic sigmoid, 0 for tanh
        #for elt in np.nditer(activated,op_flags=['readwrite']):
        #    if elt == 0: 
        #        elt[...] = 1
        return activated
    
    def _gradient(self,mat):
        w = copy.deepcopy(mat)
        for elt in np.nditer(w,op_flags=['readwrite']):
            elt[...] = elt - elt * elt
        return w
    
    def _feed_forward(self):
        data_copy = copy.deepcopy(self.data)
        print(self.num_data)
        print("Initial weights: ",self.weights)
        for i in range(0,self.num_data):
            data_col = data_copy[:,i]
            data_col = np.reshape(data_col, (-1, 1))
            prod1 = np.dot(self.weights.T,data_col)
            guess = self._activated(data_col)
            error = self.targets[i] - guess
            print("Guess: ", guess, " and target: ", self.targets[i])
            grad = self._gradient(guess)
            s = (error * self.learn_rate)[0][0] 
            print("Grad: ",grad, "\n Error:", error)
            wt_change = s * grad
            print("Weight change: ", wt_change)
            print("Pre new weightz: ", wt_change + self.weights)
            self.weights = wt_change + self.weights
            self.weights = self.weights/(np.sum(self.weights))
            print("New weights: ",self.weights)
            
        
    def _prop_backward(self):
        return None
    
    def _calc_error(self,mat):
        return None
        
        

In [668]:
# See www.cse.unsw.edu.au/~cs9417ml/MLP2/
sample_data = np.sign(1-2*np.random.rand(6,10))
sample_data[0] = sample_data[1]
# Need to write binary target values for data as well for MLP
mat_dbg(sample_data)
MLP_1 = MLP(sample_data,1,0.05)
print("Weights^T: \n",MLP_1.weights.T)
print("Targets: ")
print(MLP_1.targets)
print("Data: \n",MLP_1.data)
MLP_1._gradient(np.array([0, 1, 2, 3, 4]))

(6, 10) : 
 [[-1.  1. -1.  1.  1. -1.  1.  1. -1.  1.]
 [-1.  1. -1.  1.  1. -1.  1.  1. -1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1. -1.]
 [-1. -1.  1. -1.  1.  1. -1.  1. -1.  1.]
 [-1. -1.  1. -1.  1.  1. -1.  1. -1.  1.]
 [ 1.  1.  1.  1. -1.  1.  1. -1. -1.  1.]]
Weights^T: 
 [[ 1.          0.98576224  0.9594031   0.83024386  0.37949296  0.9569474 ]]
Targets: 
[-1.  1. -1.  1.  1. -1.  1.  1. -1.  1.]
Data: 
 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1.  1. -1.  1.  1. -1.  1.  1. -1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1. -1.]
 [-1. -1.  1. -1.  1.  1. -1.  1. -1.  1.]
 [-1. -1.  1. -1.  1.  1. -1.  1. -1.  1.]
 [ 1.  1.  1.  1. -1.  1.  1. -1. -1.  1.]]


array([  0,   0,  -2,  -6, -12])

In [669]:
#print("Weights: \n",MLP_1.weights)
#print(MLP_1.data)
#print(MLP_1.weights)
#print(MLP_1.data)
MLP_1._feed_forward()
#print(MLP_1.data)

10
Initial weights:  [[ 1.        ]
 [ 0.98576224]
 [ 0.9594031 ]
 [ 0.83024386]
 [ 0.37949296]
 [ 0.9569474 ]]
Guess:  [[ 0.67279448]]  and target:  -1.0
Grad:  [[ 0.22014207]] 
 Error: [[-1.67279448]]
Weight change:  [[-0.01841262]]
Pre new weightz:  [[ 0.98158738]
 [ 0.96734962]
 [ 0.94099048]
 [ 0.81183124]
 [ 0.36108033]
 [ 0.93853478]]
New weights:  [[ 0.19626355]
 [ 0.19341678]
 [ 0.1881464 ]
 [ 0.16232165]
 [ 0.07219623]
 [ 0.18765539]]
Guess:  [[ 0.53859096]]  and target:  1.0
Grad:  [[ 0.24851074]] 
 Error: [[ 0.46140904]]
Weight change:  [[ 0.00573326]]
Pre new weightz:  [[ 0.2019968 ]
 [ 0.19915004]
 [ 0.19387965]
 [ 0.1680549 ]
 [ 0.07792948]
 [ 0.19338865]]
New weights:  [[ 0.19527929]
 [ 0.19252719]
 [ 0.18743208]
 [ 0.16246614]
 [ 0.0753379 ]
 [ 0.1869574 ]]
Guess:  [[ 0.55973372]]  and target:  -1.0
Grad:  [[ 0.24643188]] 
 Error: [[-1.55973372]]
Weight change:  [[-0.01921841]]
Pre new weightz:  [[ 0.17606088]
 [ 0.17330878]
 [ 0.16821367]
 [ 0.14324774]
 [ 0.05611949]