In [1]:
%matplotlib inline

from __future__ import absolute_import, print_function, unicode_literals, division
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import itertools
import random as rand
import copy

In [2]:
def mat_dbg(x):
    print(x.shape, ": \n", x)

In [94]:
class MLP(object):
    """
    NOTE: Matrix operations are modified from RBM file
    In particular, we have an an an input of n data points with
    dimension d as a d-by-n matrix
    """
    def __init__(self, data, num_hidden, learn_rate):
        self.data = data
        self.num_data = data.shape[1]
        self.num_visible = data.shape[0]
        self.num_hidden = num_hidden
        self.learn_rate = learn_rate
        
        self.weights = np.random.rand(self.num_visible, self.num_hidden)
        self.weights = np.insert(self.weights, 0, 0, axis = 0)
        self.data = np.insert(self.data, 0, 1, axis = 0)
        
        #mat_dbg(self.weights.T)
        #mat_dbg(self.data)
    
    def _sigmoid(self,x):
        return 1.0/(1.0+np.exp(-x))
        
    def _activate_fun(self):
        activated = self._sigmoid(np.dot(self.weights.T,self.data)) 
        activated = np.sign(activated - 0.5)
        for elt in np.nditer(activated,op_flags=['readwrite']):
            if elt == 0:
                elt[...] = 1
        return activated
    
    def _prop_forward(self):
        return None
        
    def _prop_backward(self):
        return None
    
    def _calc_error(self):
        return None
        

In [95]:
sample_data = 1-2*np.random.rand(3,4)
mat_dbg(sample_data)
MLP_1 = MLP(sample_data,2,0.1)
MLP_1._activate_fun()

(3, 4) : 
 [[ 0.51790095  0.32054292 -0.48104622  0.48161559]
 [-0.28239893  0.65450862  0.80899291 -0.57484962]
 [-0.59582509 -0.23546264 -0.78700595 -0.09211934]]


array([[-1.,  1., -1., -1.],
       [ 1.,  1., -1., -1.]])